Add a full-route key to the request map
weavejester/compojure pull request #210
Opened 2022-04-28 16:14 UTC by liamchzh

This provides access to the full route that contains the common prefix.
The full-route info is added to the `:compojure/full-route` key in the
request map.

We use `:compojure/route` to get the route info and add it to the
attributes of our metrics and traces, but when `compojure.core/context`
is used, we are not able to get the parameters that are not
instantiated. This change adds `:compojure/full-route` key that serves
similarly as the existing `:compojure/route` does - the only difference
is that the new key has a common prefix.

Close #207

2022-04-28 16:21 UTC, liamchzh commented
Hi @weavejester, could you take a look at this PR when you have a chance?

We decided to attach meta info to the compiled route because we don't want to change `make-context`, as it is public. We could make a more direct map-based implementation if backward compatibility of `make-context` is not important.

We are not entirely sure what the full syntax is of `context`, so it's possible we're missing a case to handle in the `context-route`.

Let me know if you have any comments, thank you!

2022-04-28 20:37 UTC, weavejester commented
This looks rather complex for what it attempts to achieve. I notice that there's already a PR, #202, for adding the context route to the request map. Would that solve the issue?

2022-05-02 20:48 UTC, liamchzh commented
@weavejester I've updated my PR to pass the `path` through `make-context`(as you suggested in #202). The approach looks simpler now.

2022-05-09 18:12 UTC, weavejester commented
I got distracted by some other PRs - apologies for letting this one slip. I notice there's some formatting changes that look like they've accidentally crept in. Can you ensure the commit contains only the changes relevant to the feature being implemented?

2022-05-10 19:26 UTC, weavejester requested changes
Can you separate out the context feature into another PR?

2022-05-10 19:26 UTC, weavejester commented on src/compojure/core.clj
> +          (update :compojure/context-path (fn [ctx] (str ctx context-path)))))))
Could be simplified to:

```clojure
(update :compojure/context-path str context-path)
```

2022-05-10 19:26 UTC, weavejester commented on test/compojure/core_test.clj
> +            (is (= (dissoc r :params :route-params :compojure/route :compojure/full-route)
Keep lines within 80 characters, please.

2022-05-10 19:26 UTC, weavejester commented on src/compojure/core.clj
> +     (let [full-route (str (:compojure/context-path request) (second route-info))]
I think in another PR I suggested `:compojure/route-context`. Also better to use destructuring outside the fn rather than `second`.

2022-05-11 18:23 UTC, weavejester commented
It looks good, but it still needs to be separated out into a "full context" PR and "full route" PR, as I mentioned in my previous review.

2022-05-11 20:19 UTC, liamchzh commented
> It looks good, but it still needs to be separated out into a "full context" PR and "full route" PR, as I mentioned in my previous review.

Sure thing! I've opened #212. I will update this PR when #212 goes in.

2022-05-12 19:49 UTC, weavejester commented
I've thought about this a little, and I think it's sufficient to have `:compojure/route` and `:compojure/route-context`. The full route can be derived from those keys, so we don't need to add it as a key in an of itself.

2022-05-12 19:49 UTC, weavejester commented
I've thought about this a little, and I think it's sufficient to have `:compojure/route` and `:compojure/route-context`. The full route can be derived from those keys, so we don't need to add it as a key in an of itself.

2022-05-12 21:03 UTC, liamchzh commented
Yes, that's fair. Having the `route-context` key would address our issue. It's a bit redundant to have a `full-route` key.

I am happy to close this PR. Thanks!

2022-05-12 21:03 UTC, closed without merging

2022-05-13 20:00 UTC, liamchzh commented
Could you push a new release when you have a chance?